module.exports = { 
    usuarios: [
    {
        id: 1, 
        nome: 'Cassio',
        salario: '1000000.01',
        ativo: true,
        idade: 35,
        time: 'Corinthians',
        posicao: 'Goleiro',
        perfil: 2,
        camisa: 12,
    },
    {
        id: 2, 
        nome: 'Roger Guedes',
        salario: '800000.01',
        ativo: true,
        idade: 26,
        time: 'Corinthians',
        posicao: 'Atacante',
        perfil: 1,
        camisa: 10,
    },
    {
        id: 3, 
        nome: 'Yuri Alberto',
        salario: '700000.01',
        ativo: true,
        idade: 22,
        time: 'Corinthians',
        posicao: 'Atacante',
        perfil: 1,
        camisa: 9
    },
    {
        id: 4, 
        nome: 'Renato Augusto',
        salario: '850000.01',
        ativo: true,
        idade: 35,
        time: 'Corinthians',
        posicao: 'Meia',
        perfil: 1,
        camisa: 8,
    },
    {
        id: 5, 
        nome: 'Adson',
        salario: '400000.00',
        ativo: true,
        idade: 24,
        time: 'Corinthians',
        posicao: 'Meia',
        perfil: 2,
        camisa: 28,
    },
    ],
    perfis: [
        { id: 1, descricao: "DIREITA"},
        { id: 2, descricao: "ESQUERDA"}
    ],
};